database:
  driver: sqlite3
  connection: sample.db
  logger:
    kafka:
      brokers:
        - steamer-01.srvs.cloudkafka.com:9093
        - steamer-02.srvs.cloudkafka.com:9093
        - steamer-03.srvs.cloudkafka.com:9093
      topic: sql
trace:
  zipkin:
    collector:
      url: # endpoint typically looks like: http://zipkinhost:9411/api/v1/spans
    recoder:
      hostPort: 127.0.0.1:8080
debug: true
httpport: 8080